os:
  - linux
  - osx
dist: trusty
language: c
env:
  - TARGET=c M32=
  - TARGET=c M32=-m32
  - TARGET=x86 OS=linux M32=
  - TARGET=x86 OS=linux M32=-m32
  - TARGET=arm OS=linux M32=-m32
  - TARGET=m68k OS=linux M32=-m32
  - TARGET=riscv OS=linux M32=-m32
  - TARGET=pdp11 OS=unix M32=-m32 CHECK=check-16-bit
  - TARGET=asmjs M32= JS=js24
  - TARGET=asmjs M32=-m32 JS=js24
  - TARGET=asmjs M32=-m32 JS=nodejs
# - TARGET=asmjs M32=-m32 JS=/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Resources/jsc
matrix:
  exclude:
    - os: osx
      env: TARGET=x86 OS=linux M32=
    - os: osx
      env: TARGET=x86 OS=linux M32=-m32
    - os: osx
      env: TARGET=arm OS=linux M32=-m32
    - os: osx
      env: TARGET=m68k OS=linux M32=-m32
    - os: osx
      env: TARGET=riscv OS=linux M32=-m32
    - os: osx
      env: TARGET=pdp11 OS=unix M32=-m32 CHECK=check-16-bit
    - os: osx
      env: TARGET=asmjs M32= JS=js24
    - os: osx
      env: TARGET=asmjs M32=-m32 JS=js24
    - os: osx
      env: TARGET=asmjs M32=-m32 JS=nodejs
install: sh -e install-deps.sh install_${TRAVIS_OS_NAME:-linux}
script: make ${CHECK:-check}  M32=$M32 TARGET=$TARGET OS=$OS
notifications:
  email: lars@nocrew.org
