os:
  - linux
  - osx
language: c
env:
  matrix:
    - M32=
    - M32=-m32
install: sh -e .travis.sh install_${TRAVIS_OS_NAME:-linux}
script: make check  M32=$M32
notifications:
  email: lars@nocrew.org
